[WIP][AUT-3124] extend charts with fission deployment
cloudentity/acp-helm-charts pull request #104
Opened 2021-11-03 12:19 UTC by ppodbielski-cloudentity

2021-11-03 15:45 UTC, mbilski requested changes
The values.yaml should contain only the minimal configuration and allow to configure critical points.

2021-11-04 09:57 UTC, ppodbielski-cloudentity commented
`# Source: acp/templates/fission.yaml
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: nodejs
spec:
  version: 1
  imagepullsecret: 
  poolsize: 3
  terminationGracePeriod: 1
  runtime:
    image: docker pull fission/node-env:latest
    podspec:
      containers:
        - name: nodejs
          imagePullPolicy: Always

apiVersion: fission.io/v1
kind: Environment
metadata:
  name: rego
spec:
  version: 1
  imagepullsecret: artifactory
  poolsize: 3
  terminationGracePeriod: 1
  runtime:
    image: docker.cloudentity.io/rego-env:latest3
    podspec:
      containers:
        - name: rego
          imagePullPolicy: Always`

2021-11-30 08:34 UTC, artursmolarek approved these changes

2021-11-30 08:49 UTC, jkotiuk approved these changes

2021-11-30 09:04 UTC, mbilski approved these changes

2021-11-30 09:05 UTC, mbilski requested changes
I don't see any changes in acp deployment which would enable fission.
What about RBAC roles that acp needs?

2021-11-30 14:01 UTC, mbilski approved these changes

2021-11-30 14:01 UTC, mbilski commented
FYI this configuration works only with acp 1.16+, not 1.15.x

2021-11-30 14:21 UTC, jkotiuk approved these changes

2021-11-30 14:34 UTC, plandzwojczak-cloudentity commented on charts/acp/README.md
> +To see all configurable options with detailed comments, visit the chart's [values.yaml](./values.yaml), fission sectoion. By default Fission Environment for ACP is disabled. To enable switch the flag
typo

2021-11-30 14:34 UTC, plandzwojczak-cloudentity commented on charts/acp/README.md
> +To manually configure Docker credentials, first createreate a Secret by providing credentials on the command line:
typo `createreate`

2021-11-30 15:03 UTC, plandzwojczak-cloudentity approved these changes

2021-11-30 15:04 UTC, merged