AUT-3116/add GitHub workflow for testing
cloudentity/acp-helm-charts pull request #136
Opened 2022-01-24 17:08 UTC by lisocki

## Jira task - https://cloudentity.atlassian.net/browse/AUT-3116

## Description

1. Added Makefile
2. Added GitHub Actions workflow for testing PRs

## Type of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Tests (extending the test suite)
- [ ] Refactor (internal improvement that doesn't change product functionality)
- [ ] Other (if none of the other choices apply)

## Implementation details

## Screenshots (if appropriate):

2022-01-25 08:07 UTC, ppodbielski-cloudentity approved these changes

2022-01-25 08:43 UTC, artursmolarek requested changes
As we discussed, please avoid code duplication and use https://github.com/cloudentity/acp-on-k8s to spin up the cluster.

2022-02-23 08:31 UTC, mbilski requested changes
Please use helm testing best practices instead of using the pattern created in acp-on-k8s

2022-03-01 15:47 UTC, jkotiuk commented on config/kube-acp-stack.yaml
> +  importJob:
Should we use acp-cd instead legacy import job? @ppodbielski-cloudentity @mbilski

2022-03-01 15:48 UTC, jkotiuk commented on config/kube-acp-stack.yaml
> +hazelcast:
we should use redis

2022-03-10 07:59 UTC, closed without merging