Feature/aut 4908 standalone authorizer
cloudentity/acp-helm-charts pull request #141
Opened 2022-02-09 14:52 UTC by jkotiuk

## Jira task - https://cloudentity.atlassian.net/browse/AUT-4908

## Description

Add helm chart for standalone authorizer.

## Type of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Tests (extending the test suite)
- [ ] Refactor (internal improvement that doesn't change product functionality)
- [ ] Other (if none of the other choices apply)

2022-02-09 15:40 UTC, ppodbielski-cloudentity commented on charts/standalone-authorizer/templates/deployment.yaml
> +          {{- range $key, $value := .Values.extraEnv }}
@holowinski do we want to use env? as I remember you mention that we want to use configmap only

2022-02-09 15:43 UTC, ppodbielski-cloudentity commented on charts/standalone-authorizer/values.yaml
> +##
## double

2022-02-09 16:13 UTC, sburke-ce commented on charts/standalone-authorizer/values.yaml
> +## There is no harm in specifying them, even if you do not use a vanity domain.
`terverID` -> `serverID`.  Are there any other concerns?

2022-02-10 04:26 UTC, sburke-ce approved these changes

2022-02-10 07:33 UTC, ppodbielski-cloudentity commented on charts/standalone-authorizer/values.yaml
> +affinity: {}
acp:
```  ## Affinity for pod assignment
  affinity: {}
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: fission
  #               operator: In
  #              values:
  #                 - "true"
  ```

2022-02-23 08:29 UTC, mbilski requested changes
This helm chart should match istio-authorizer. There were lots of changes there recently

2022-04-19 07:21 UTC, closed without merging