fix for timescaledb forbidden error
cloudentity/acp-helm-charts pull request #237
Opened 2023-01-25 13:24 UTC by smalunjkarcloudentity

## Jira task -https://cloudentity.atlassian.net/browse/AUT-7133

## Implementation details (internal)
Fix for forbiden error.

## Information for QA

- [ ] Is QA testing required?
- [ ] Does PR contain unit tests?
- [ ] Should QA create E2E tests for the change?

## Additional QA Procedures (Optional)

## Screenshots (if appropriate):

2023-01-25 13:25 UTC, ppodbielski-cloudentity approved these changes

2023-01-25 13:48 UTC, artursmolarek approved these changes

2023-01-26 14:32 UTC, lgonczarik approved these changes

2023-01-31 10:49 UTC, lgonczarik requested changes
This PR fixes just one thing about the timescale.
There is an issue described by Wojtek Obara with setup of timescale (not init of timescale from acp side, so this PR do not fix it)

```log
timescaledb 2023-01-25 09:26:44,573 ERROR: create_config_service failed          
```

2023-01-31 11:26 UTC, lgonczarik approved these changes

2023-01-31 12:21 UTC, smalunjkarcloudentity commented
> This PR fixes just one thing about the timescale. There is an issue described by Wojtek Obara with setup of timescale (not init of timescale from acp side, so this PR do not fix it)
> 
> ```
> timescaledb 2023-01-25 09:26:44,573 ERROR: create_config_service failed          
> ```

@lgonczarik - when I tried it on my local it does throw that error. To my understanding that error was because of two reason, one is timescale db url in acp and second is the know issues with timescale db helm chart. Both of them are covered here. Please let me know if I am missing something, we will cover that before we merge it.

2023-01-31 12:47 UTC, lgonczarik commented
> > This PR fixes just one thing about the timescale. There is an issue described by Wojtek Obara with setup of timescale (not init of timescale from acp side, so this PR do not fix it)
> > ```
> > timescaledb 2023-01-25 09:26:44,573 ERROR: create_config_service failed          
> > ```
> 
> @lgonczarik - when I tried it on my local it does not throw that specific error anymore. To my understanding that error was because of two reason, one is timescale db url in acp and second is the know issues with timescale db helm chart. Both of them are covered here. Please let me know if I am missing something, we will cover that before we merge it.
> 
> Also "All checks have passed" so I assume the pods are coming up properly.

ACP is unable to connect to smilingly running timescaledb
```
│ timescaledb 2023-01-31 12:45:18,512 ERROR: create_config_service failed                                                                                                                                         │
│ timescaledb Traceback (most recent call last):                                                                                                                                                                  │
│ timescaledb   File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 950, in _create_config_service                                                                                              │
│ timescaledb     if not self._api.create_namespaced_service(self._namespace, body):                                                                                                                              │
│ timescaledb   File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 483, in wrapper                                                                                                             │
│ timescaledb     return getattr(self._core_v1_api, func)(*args, **kwargs)                                                                                                                                        │
│ timescaledb   File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 419, in wrapper                                                                                                             │
│ timescaledb     return self._api_client.call_api(method, path, headers, body, **kwargs)                                                                                                                         │
│ timescaledb   File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 388, in call_api                                                                                                            │
│ timescaledb     return self._handle_server_response(response, _preload_content)                                                                                                                                 │
│ timescaledb   File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 218, in _handle_server_response                                                                                             │
│ timescaledb     raise k8s_client.rest.ApiException(http_resp=response)                                                                                                                                          │
│ timescaledb patroni.dcs.kubernetes.K8sClient.rest.ApiException: (403)                                                                                                                                           │
│ timescaledb Reason: Forbidden                                                                                                                                                                                   │
│ timescaledb HTTP response headers: HTTPHeaderDict({'Audit-Id': 'f8763584-888c-4eee-8c07-b6a751c8cb26', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nos │
│ niff', 'X-Kubernetes-Pf-Flowschema-Uid': '05872dd4-6d17-4cdd-9260-866771f9bc8d', 'X-Kubernetes-Pf-Prioritylevel-Uid': '157ba6c7-6db4-47c0-9ec2-b2e3f9053d03', 'Date': 'Tue, 31 Jan 2023 12:45:18 GMT', 'Content │
│ -Length': '304'})                                                                                                                                                                                               │
│ timescaledb HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \\"system:serviceaccount:acp-system:timescale\\" cannot create res │
│ ource \\"services\\" in API group \\"\\" in the namespace \\"acp-system\\"","reason":"Forbidden","details":{"kind":"services"},"code":403}\n'                                                                   │
│ timescaledb    
```
as you can see, it has some issue with kubernetes permissions IMO.
@awwkoala @wobara-cloudentity an I tested it locally and the same issue occurs;
(acp fails with: `│ {"error":"dial tcp 127.0.0.1:5432: connect: connection refused","level":"fatal","msg":"failed to run ./migrations/timescale migrations","time":"2023-01-31T12:47:08Z"}`)

2023-01-31 13:46 UTC, lgonczarik approved these changes

2023-01-31 14:02 UTC, merged