AUT-2970 Add import job to acp chart
cloudentity/acp-helm-charts pull request #68
Opened 2021-06-16 21:31 UTC by dzeromski-cloudentity

2021-06-17 06:13 UTC, mbilski requested changes

2021-06-17 06:13 UTC, mbilski commented on charts/acp/values.yaml
> +  data:
lets change it to sth like this
```
importJob:
  enabled: false
  # the data should match import configuration endpoint request body
  # https://docs.authorization.cloudentity.com/api/system/#operation/importConfiguration
  data: 
    tenants: []
    servers: []
    clients: []
```
as this example won't work like this

2021-06-17 07:16 UTC, ppodbielski-cloudentity approved these changes

2021-06-21 19:34 UTC, holowinski commented
Could you tell me what's the motivation behind this? @mbilski @dzeromski-cloudentity

2021-06-22 16:35 UTC, mbilski approved these changes

2021-06-24 07:56 UTC, artursmolarek approved these changes

2021-06-29 20:27 UTC, holowinski commented
@dzeromski-cloudentity can we update and merge this?

2021-07-13 14:43 UTC, merged